import Head from "next/head";
import { useEffect, useState } from "react";
import Homepage from "@/components/Homepage";
import { useRouter } from "next/router";

export default function Home() {
  const [logged, setLogged] = useState();
  const [user, setUser] = useState();

  const router = useRouter();

  useEffect(() => {
    async function fetchData() {
      const token = localStorage.getItem("token");

      const bodyData = {
        token: token || "",
      };

      const data = await fetch("http://localhost:3000/api/auth/test", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(bodyData),
      }).then((res) => res.json());

      if (data.code == 400) {
        router.push("/login");
        setLogged(false);
      } else {
        localStorage.setItem("id", data.user.id);
        setLogged(true);
      }

      setUser(data.user);
    }

    fetchData();
  }, []);

  return (
    <div className="flex flex-col">
      <Head>
        <title>Home - OdinBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {logged == false ? <></> : <Homepage user={user} />}
    </div>
  );
}
