import Head from "next/head";
import { useEffect } from "react";
import Homepage from "@/components/Homepage";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";

export default function Home() {
  const { userInfo } = useSelector((state) => state.auth);

  useEffect(() => {
    if (!userInfo) {
      router.push("/login");
    }
  }, [userInfo]);

  const router = useRouter();

  return (
    <div className="flex flex-col">
      <Head>
        <title>Home - OdinBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!userInfo ? <></> : <Homepage user={userInfo} />}
    </div>
  );
}
